# For local development purposes only!
version: '3.8'
services:
  postgres:
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - /app/node_modules
      - /app/frontend/node_modules
      - .:/app
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on: 
      - postgres
    environment: 
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_SYNCHRONIZE=true
    ports:
      - 3001:3001
    volumes: 
      - /app/node_modules
      - /app/backend/node_modules
      - .:/app


volumes: 
  postgres: