# For local development purposes only!
version: '3.8'
services:
  proxy:
    build: 
      context: ./proxy
    ports: 
      - 9000:80
    depends_on: 
      - s3
  s3:
    image: minio/minio:latest
    volumes: 
      - s3:/data
    command: server /data --console-address=":9001" 
    environment: 
      - MINIO_ROOT_USER=access_key
      - MINIO_ROOT_PASSWORD=secret_key
    ports: 
      - 9001:9001
  # Creates buckets and sets policy for viewing objects
  setup-s3:
    image: minio/mc
    depends_on: 
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add s3 http://s3:9000 access_key secret_key;
      /usr/bin/mc mb s3/nuscats;
      /usr/bin/mc policy set download s3/nuscats;
      exit 0;
      "
  postgres:
    image: postgis/postgis
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes: 
      - /app/node_modules
      - /app/frontend/node_modules
      - .:/app
    ports: 
      - 3000:3000
    env_file:
      - frontend/.env
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on: 
      - postgres
      - s3
      - setup-s3
    environment: 
      # Database Configuration
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DB_SYNCHRONIZE=true
      # JWT Configuration
      - JWT_ACCESS_TOKEN_SECRET=accSecret
      - JWT_REFRESH_TOKEN_SECRET=refSecret
      - JWT_MAIL_VERIFY_SECRET=mailSecret
      - JWT_PASSWORD_RESET_SECRET=pwSecret
      # Object Storage Configuration
      - AWS_REGION=ap-southeast-1
      - AWS_S3_ENDPOINT=http://localhost:9000
      - AWS_ACCESS_KEY_ID=access_key
      - AWS_SECRET_ACCESS_KEY=secret_key
      - AWS_S3_SIGNATURE_VERSION=v4
      - AWS_S3_BUCKET_NAME=nuscats
      # Should seed
      - SEEDER_SHOULD_SEED=false
      - SEEDER_SHOULD_REFRESH=false
      # App variables
      - CLIENT_URL=http://localhost:3000
    ports: 
      - 3001:3001
    volumes: 
      - /app/node_modules
      - /app/backend/node_modules
      - .:/app


volumes: 
  s3:
  postgres: